---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: install ntp
    yum: name=ntp state=installed update_cache=yes

  - name: start ntp
    service: name=ntp state=started

  handlers:

  - name: restart ntp
    service: name=ntp state=restarted
